[package]
name = "snake-game"
version = "0.1.0"
authors = ["RohanXKapur <rohankapurdev@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"
piston_window ="0.117.0"